### ISSUE TITLE
Issues connecting from IPFS nodes over WSS

### ISSUE THREAD

**Issue by TheDiscordian** [libp2p/go-libp2p-relay-daemon#18] opened 2022-06-20 20:48 UTC
Commit: a32147234644cfef5b42a9f5ccaf99b6e6021fd4

**Issue:**

Both js-ipfs and go-ipfs refuse to connect to this relay node over wss, works fine over ws.

**What was tried:**

Both go-ipfs and js-ipfs were tried, or simply: `ipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A`:

Kubo 0.12 fails to connect:

```console
$ ipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A
error: connect 12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A failure: no good addresses
```

To debug @lidel tried `websocat`:

```
$ websocat wss://ipfs.thedisco.zone:4430/ 
/multistream/1.0.0
```

But it indicates it should be working correctly. We also tried regular websockets, and those work fine. The reverse proxy server in use is Nginx.

Just in case, I tried to also update the cert, but this didn't change anything. It's worth noting that this is the exact same setup I was using with go-ipfs for relaying, and it was working fine. Config files provided below.

**Configs:**

config.json:
```
{
  "RelayV2": {
    "Enabled": false
  },
  "RelayV1": {
    "Enabled": true
  },
  "Network": {
    "ListenAddrs": [
        "/ip4/0.0.0.0/tcp/4011/ws",
        "/ip6/::/tcp/4011/ws"
    ],
    "AnnounceAddrs": [
	"/dns6/ipfs.thedisco.zone/tcp/4430/wss",
	"/dns4/ipfs.thedisco.zone/tcp/4430/wss"
    ]
  },
  "Daemon": {
    "PprofPort": -1
  }
}
```

/etc/nginx/sites-enabled/ipfs:
```
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
 
    upstream websocket {
        server 127.0.0.1:4011;
    }

map $remote_addr $proxy_forwarded_elem {
    # IPv4 addresses can be sent as-is
    ~^[0-9.]+$          "for=$remote_addr";

    # IPv6 addresses need to be bracketed and quoted
    ~^[0-9A-Fa-f:.]+$   "for=\"[$remote_addr]\"";

    # Unix domain socket names cannot be represented in RFC 7239 syntax
    default             "for=unknown";
}

map $http_forwarded $proxy_add_forwarded {
    # If the incoming Forwarded header is syntactically valid, append to it
    "~^(,[ \\t]*)*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*([ \\t]*,([ \\t]*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*)?)*$" "$http_forwarded, $proxy_forwarded_elem";

    # Otherwise, replace it
    default "$proxy_forwarded_elem";
}
 
    server {
        listen 4430 ssl;
        ssl_certificate /etc/letsencrypt/live/ipfs.thedisco.zone/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/ipfs.thedisco.zone/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
        location / {
            proxy_set_header Forwarded $proxy_add_forwarded;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
        }
    }
```

**Comment by TheDiscordian** [comment] 2022-06-20 20:50
Forgot to add, here's a minimal test for `js-ipfs` that returns the following error: `Uncaught (in promise) AggregateError: No Promise in Promise.any was resolved`



HTML:

```html
<!DOCTYPE html>
<html lang="en">
<head><title>js-ipfs minimal relay test</title>

<script src="https://cdn.jsdelivr.net/npm/ipfs-core@0.15.2/dist/index.min.js"></script>

<script>
var ipfs;
async function main() {
	ipfs = await window.IpfsCore.create();
	await ipfs.swarm.connect("/dns6/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A");
}
main()
</script>
</head>
</html>
```

**Comment by marten-seemann** [comment] 2022-06-20 20:53
Why are you using a reverse proxy? The WebSocket transport now supports WSS.

**Comment by TheDiscordian** [comment] 2022-06-20 20:53
@marten-seemann can you link me to docs for how to point it to my cert please? ❤️ I wasn't aware that I could ditch the reverse proxy now.

**Comment by marten-seemann** [comment] 2022-06-20 21:16
Here's the option: https://github.com/libp2p/go-libp2p/blob/707100a521dace4a7a87fd17c04042ea483380b5/p2p/transport/websocket/websocket.go#L56-L62

In code, this would look something like:
```go
libp2p.New(
    libp2p.Transport(ws.New, ws.WithTLSConfig(tlsConf)),
    ....
)
```

**Comment by aschmahmann** [comment] 2022-06-21 03:31
@TheDiscordian you will not be able to connect to a WSS node from go-ipfs without doing a bunch of work because go-libp2p could not dial WSS addresses authenticated by DNS addresses until we merged https://github.com/libp2p/go-libp2p/pull/1592 which was recent and therefore not yet released.

I ran `vole.exe bitswap check bafkqaaa /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A` (using
https://github.com/aschmahmann/vole/pull/18) and got a connection just fine. There's a `protocol not supported` error but that's just because it doesn't speak Bitswap which is... correct for the relay 😄.

**Comment by TheDiscordian** [comment] 2022-06-21 15:10
@marten-seemann Thanks! I'll work on ditching the reverse proxy today, and see if that narrows anything down (it'll be nice to axe Nginx)

@aschmahmann Ah thanks! This explains why go-ipfs failed, but not js-ipfs 🤔. Will try again with Marten's tip...

**Comment by marten-seemann** [comment] 2022-06-22 10:54
> js-ipfs now returns a very unexpected error: Uncaught (in promise) Error: no protocol with name: "'dns'". Must have a valid family name: "{ip4, ip6, dns4, dns6}".

Looks like JS expects an IP address, not a domain name. The domain name is needed though to allow the browser to verify the certificate. @achingbrain, this seems like bug in js-libp2p, doesn't it?

**Comment by lidel** [comment] 2022-06-24 15:01
Related issues:
- JS: https://github.com/multiformats/js-multiaddr/pull/253
- GO: https://github.com/multiformats/go-multiaddr-dns/issues/47

**Comment by lidel** [comment] 2022-08-01 19:21
- I believe relevant bug got fixed in https://github.com/libp2p/go-libp2p/pull/1612/files#diff-8a203f70505b8dae3ee69421aa2326392c2f301091f557e44649fa40205f246fR26 
  - This was released in go-libp2p 0.20.3, I will open a PR that bumps the dependency

**Comment by lidel** [comment] 2022-08-05 19:50
@TheDiscordian after JS part is shipped, please make sure you update to [libp2p-relay-daemon v0.2.0](https://github.com/libp2p/go-libp2p-relay-daemon/releases/tag/v0.2.0)  before you re-test things end-to-end. This way, we also confirm the latest go-libp2p works fine :crossed_fingers:

**Comment by lidel** [comment] 2022-08-08 15:42
After we confirm this is fixed, we need to add smoke/regression test that dialls `/dns/.../wss` from js-ipfs and Kubo (tbd if this should live  in their respective repos, or in https://github.com/ipfs/interop)

**Comment by TheDiscordian** [comment] 2022-10-04 17:02
@lidel @achingbrain this appears to be unresolved for js-ipfs, any theories?

Repo used: https://github.com/TheDiscordian/go-libp2p-relay-daemon

Code:

```html
<!DOCTYPE html>
<html lang="en">
<head><title>js-ipfs minimal relay test</title>

<script src="https://cdn.jsdelivr.net/npm/ipfs-core@0.16.1/dist/index.min.js"></script>

<script>
var ipfs;
async function main() {
	ipfs = await window.IpfsCore.create();
	await ipfs.swarm.connect("/dns6/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A");
}
main()
</script>
</head>
</html>
```

I can confirm this works fine /w Kubo. Error is the same as before, Chrome:
<img width="854" alt="Screen Shot 2022-10-04 at 1 00 34 PM" src="https://user-images.githubusercontent.com/43145244/193881331-b5c58d8d-b737-4d78-b054-e4b6a2ac69e5.png">

Firefox:

![Screen Shot 2022-10-04 at 1 01 29 PM](https://user-images.githubusercontent.com/43145244/193881523-a63ee4b8-4148-4a41-9127-a07ff66ea42c.png)

**Comment by 2color** [comment] 2022-10-04 17:12
> I can confirm this works fine /w Kubo. Error is the same as before /w js-ipfs, Chrome:

So both Kubo and js-ipfs daemons are able to connect to `/dns6/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A` But js-ipfs in the browser fails to connect?

**Comment by TheDiscordian** [comment] 2022-10-04 17:13
@2color I haven't actually tested the js-ipfs daemon, only the browser. However yes, Kubo definitely works fine, I can connect and see the node in my list of peers.

**Comment by lidel** [comment] 2022-10-05 14:18
jsipfs daemon fails too:

```console
$ ipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A
connect 12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A success

$  jsipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A
(node:16151) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
fetch failed
```

**Comment by lidel** [comment] 2022-10-05 14:20
@achingbrain  I wonder if JS side of things needs to implement the `/sni/` fix from https://github.com/libp2p/go-libp2p/pull/1719 ?

**Comment by marten-seemann** [comment] 2022-10-05 15:34
> @achingbrain I wonder if JS side of things needs to implement the /sni/ fix from https://github.com/libp2p/go-libp2p/pull/1719 ?

It's only used internally, although one _could_ announce addresses containing `/sni`.

**Comment by BigLep** [comment] 2022-10-14 16:59
> * [ ]  After we confirm this is fixed, we need to add smoke/regression test that dialls `/dns/.../wss` from js-ipfs and Kubo (tbd if this should live  in their respective repos, or in https://github.com/ipfs/interop)

@lidel : I wish I knew the answer myself, but would you please be able to outline what tests are needed where so we don't regress on this in the future?  I am then game to engage with the teams to make sure we harder ourselves here.  Thanks.

**Comment by p-shahi** [comment] 2022-11-02 16:45
go-libp2p v0.23.3 has been released https://github.com/libp2p/go-libp2p/releases/tag/v0.23.3 which incorporates @thibmeu 's fix for the missing HTTP Host header in `/wss`

**Closed** 2024-09-05 19:07 UTC
